language = 'he'
name = 'Hebrew'
rtl = true

variants.default.display = 'default'

[[mappings]]

'א' = "a"
'ב' = ["b", "v"]
'ג' = "g"
'ד' = "d"
'ה' = "h"
'ו' = ["o", "u"]
'ז' = "z"
'ח' = "x"
'ט' = "T"
'י' = ["i", "j"]
'כ' = "k"
'ך' = "K"
'ל' = "l"
'מ' = "m"
'ם' = "M"

[[mappings]]

'נ' = "n"
'ן' = "N"
'ס' = "s"
'ע' = "y"
'פ' = ["f", "p"]
'ף' = ["F", "P"]
'צ' = "c"
'ץ' = "C"
'ק' = "q"
'ר' = "r"
'ש' = "w"
'ת' = "t"
'־' = "e-"
'׳' = ["G", "e'"]
'״' = ["GG", 'e"']
'﬩' = "e+"

[[mappings]]

'ְ' = "E"
'ֵ' = "EE"
'ֶ' = "EEE"
'ֱ' = "EEEE"
'ַ' = "A"
'ָ' = "AA"
'ֲ' = "AE"
'ֳ' = "AAE"
'ִ' = "I"
'ֹ' = "O"
'וֺ' = ["oeo", "ueo"]
'ֻ' = "U"
'ּ' = "D"
'שׁ' = "W"
'שׂ' = "S"

[display_override]
#'וֺ' = ['וֺ', ["oeo", "ueo", "<small><font size=\"0.3em\">(see below)</font></small>"]]

[footer]

content = """<div dir="ltr">
❗️Use <code>O</code> to add <i>holam</i> to all letters. To use <i>holam haser</i> with <code>ו</code>
type <code>oeo</code> or <code>ueo</code>. This produces <code>וֺ</code>, as opposed to normal <code>וֹ</code>.
</div>
"""
