language = 'he'
name = 'Hebrew'
rtl = true

variants.default.display = 'default'

[[mappings]]

'א' = "a"
'ב' = ["b", "v"]
'ג' = "g"
'ד' = "d"
'ה' = "h"
'ו' = ["o", "u"]
'ז' = "z"
'ח' = "x"
'ט' = "T"
'י' = ["i", "j"]
'כ' = "k"
'ך' = "K"
'ל' = "l"
'מ' = "m"
'ם' = "M"

[[mappings]]

'נ' = "n"
'ן' = "N"
'ס' = "s"
'ע' = "y"
'פ' = ["f", "p"]
'ף' = ["F", "P"]
'צ' = "c"
'ץ' = "C"
'ק' = "q"
'ר' = "r"
'ש' = "w"
'ת' = "t"

[[mappings]]

'ְ' = "E"
'ֵ' = "EE"
'ֶ' = "EEE"
'ֱ' = "EEEE"
'ַ' = "EA"
'ָ' = "EAA"
'ֲ' = "EAE"
'ֳ' = "EAAE"
'ִ' = "EI"
'ֹ' = "EO"
'ֻ' = "EU"
'ּ' = "ED"
'ׂ' = "ES"
'ׁ' = "EW"
'׳' = "G"
'״' = "GG"

[display_override]
'ׂ' = ['שׂ', ["wES"]]
'ׁ' = ['שׁ', ["wEW"]]
