language = 'ru'
name = 'Russian'

variants.default.display = 'default'
variants.'translit-ru'.display = 'translit.ru'

[[mappings]]

'А' = 'A'                                               #  1
'а' = 'a'
'Б' = 'B'                                               #  2
'б' = 'b'
'В' = 'V'                                               #  3
'в' = 'v'
'Г' = 'G'                                               #  4
'г' = "g"
'Д' = "D"                                               #  5
'д' = "d"
'Е' = "E"                                               #  6
'е' = "e"
'Ё' = [["Jo", "JO"], ["Yo", "YO"], "Ö", "Ë"]            #  7
'ё' = ["jo", "yo", "ö", "ë"]
'Ж' = [["Zh", "ZH"]]                                    #  8
'ж' = "zh"

[[mappings]]

'З' = "Z"                                               #  9
'з' = "z"
'И' = "I"                                               # 10
'и' = "i"
'Й' = "J"                                               # 11
'й' = "j"
'К' = "K"                                               # 12
'к' = "k"
'Л' = "L"                                               # 13
'л' = "l"
'М' = "M"                                               # 14
'м' = "m"
'Н' = "N"                                               # 15
'н' = "n"
'О' = "O"                                               # 16
'о' = "o"

[[mappings]]

'П' = "P"                                               # 17
'п' = "p"
'Р' = "R"                                               # 18
'р' = "r"
'С' = "S"                                               # 19
'с' = "s"
'Т' = "T"                                               # 20
'т' = "t"
'У' = "U"                                               # 21
'у' = "u"
'Ф' = "F"                                               # 22
'ф' = "f"
'Х' = ["H", "X"]                                        # 23
'х' = ["h", "x"]
'Ц' = "C"                                               # 24
'ц' = "c"

[[mappings]]

'Ч' = [["Ch", "CH"]]                                    # 25
'ч' = "ch"
'Ш' = [["Sh", "SH"]]                                    # 26
'ш' = "sh"
'Щ' = ["W", ["Shh", "SHh", "SHH"]]                      # 27
'щ' = ["w", "shh"]

'Ъ'.default = [["Qq", "QQ"]]                            # 28
'Ъ'.'translit-ru' = "##"
'ъ'.default = "qq"
'ъ'.'translit-ru' = ["#", "tvz"]

'Ы' = "Y"                                               # 29
'ы' = "y"

'Ь'.default = "Q"                                       # 30
'Ь'.'translit-ru' = "''" 
'ь'.default = "q"
'ь'.'translit-ru' = ["'", "mjz"]

'Э' = [["Je", "JE"], "Ä"]                               # 31
'э' = ["je", "ä"]
'Ю' = [["Ju", "JU"], ["Yu", "YU"], "Ü"]                 # 32
'ю' = ["ju", "yu", "ü"]

'Я'.default = [["Ja", "JA"], ["Ya", "YA"]]              # 33
'Я'.'translit-ru' = [["Ja", "JA"], ["Ya", "YA"], "Q"]
'я'.default = ["ja", "ya"]
'я'.'translit-ru' = ["ja", "ya", "q"]

[footer]

content = """
❗️To enter combinations such as <code>сх</code> or <code>шх</code> press <code>ESC</code>
after the first letter to stop recognition. That is <code>s\u00A0ESC\u00A0h</code> will
produce <code>сх</code> and <code>sh\u00A0ESC\u00A0h</code> will produce <code>шх</code>.
"""
