#! /bin/bash

# Copyright (c) 2023, Eugene Gershnik
# SPDX-License-Identifier: GPL-3.0-or-later

set -e

"$2/Library/Input Methods/Translit.app/Contents/MacOS/Translit" --register || echo failed registration

